# print(-1,0,1)
# print(-1,0,1)


# print(3*2)
# print("풍선")
# print('나비')

# print(1 > 10)

# print("우리집에는 강아지가 있는데, 이름이 학교이에요")
# print("우리집에는 강아지가 있는데, 이름이 학교이에요")
# print("우리집에는 강아지가 있는데, 이름이 학교이에요")
# print("우리집에는 강아지가 있는데, 이름이 학교이에요")

# subway = ["유재석", "조세호", "박명수"]
# print(subway)
# print(subway)
# print(subway.index("박명수"))

# print(subway.pop())
# print(subway)

# print("나는 무엇을{} 하고 있는{} 것일까".format("파란", "빨간"))

# mix_list = ["조세호", 20, True]
# mix_list.reverse()
# print(mix_list)

# from ast import Dict

# dic = {}
# dic[1] = "박경전"
# dic[2] = "박경전"


# print(dic)

from random import shuffle
from this import d


java = {"a", "b", "c", "d"}
python = {"c", "d", "e", "f"}

print(java & python)

print(java, type(java))

print(java, type(java))

list(java)
shuffle(java)

